# Generated by Django 5.0.4 on 2024-04-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("federal", "0002_district_code_district_district_name_ne_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("verified", models.BooleanField(default=False)),
                ("public", models.BooleanField(default=False)),
                ("startedon", models.DateTimeField()),
                ("expireon", models.DateTimeField(blank=True, null=True)),
                ("referenceType", models.CharField(max_length=255)),
                ("created_by", models.CharField(max_length=255)),
                ("updated_by", models.CharField(max_length=255)),
                ("wards", models.ManyToManyField(to="federal.ward")),
            ],
        ),
    ]
