# Generated by Django 5.0.4 on 2024-05-02 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(max_length=255)),
                ("title_ne", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "designation_ne",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("office", models.CharField(blank=True, max_length=100, null=True)),
                ("office_ne", models.CharField(blank=True, max_length=100, null=True)),
                ("is_executive_committee", models.BooleanField(default=False)),
                ("is_national_council", models.BooleanField(default=True)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(max_length=255)),
                ("title_ne", models.TextField(max_length=255)),
                ("color", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingCertificate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("certificate", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="TrainingOrg",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(max_length=255)),
                ("title_ne", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CommiteProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_ne", models.CharField(max_length=100)),
                ("additional_info", models.TextField()),
                ("additional_info_ne", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("order", models.IntegerField()),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="profiles.designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExecutiveCommitteHead",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_ne", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="profiles.designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InformationOfficer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_ne", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="profiles.designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NationalCouncilHead",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_ne", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="profiles.designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfficersHead",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_ne", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="profiles.designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfficersSpokesPerson",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_ne", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="profiles.designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trainings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(max_length=255)),
                ("title_ne", models.TextField(max_length=255)),
                ("description", models.TextField()),
                ("description_ne", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "training_certificate",
                    models.ManyToManyField(to="profiles.trainingcertificate"),
                ),
                (
                    "training_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="profiles.trainingorg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfficerProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_ne", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("additional_info", models.TextField()),
                ("additional_info_ne", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("from_date", models.DateField()),
                ("to_date", models.DateField(blank=True, null=True)),
                ("order", models.IntegerField()),
                ("departments", models.ManyToManyField(to="profiles.department")),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="profiles.designation",
                    ),
                ),
                ("skills", models.ManyToManyField(to="profiles.skills")),
                ("trainings", models.ManyToManyField(to="profiles.trainings")),
            ],
        ),
    ]
