# Generated by Django 5.0.4 on 2024-05-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="title_ne",
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="officerprofile",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="officerprofile",
            name="trainings",
            field=models.ManyToManyField(
                blank=True, null=True, to="profiles.trainings"
            ),
        ),
        migrations.AlterField(
            model_name="trainingorg",
            name="title",
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="trainings",
            name="title",
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
