# Generated by Django 5.0.4 on 2024-05-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_designation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="executivecommittehead",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executivecommittehead",
            name="additional_info_ne",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="informationofficer",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="informationofficer",
            name="additional_info_ne",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nationalcouncilhead",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nationalcouncilhead",
            name="additional_info_ne",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officershead",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officershead",
            name="additional_info_ne",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officersspokesperson",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officersspokesperson",
            name="additional_info_ne",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commiteprofile",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commiteprofile",
            name="additional_info_ne",
            field=models.TextField(blank=True, null=True),
        ),
    ]
