# Generated by Django 5.0.4 on 2024-05-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_executivecommittehead_additional_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="executivecommittehead",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="informationofficer",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="nationalcouncilhead",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="officershead",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="officersspokesperson",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="commiteprofile",
            name="image",
            field=models.ImageField(upload_to="uploads/profiles/prof"),
        ),
        migrations.AlterField(
            model_name="commiteprofile",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="executivecommittehead",
            name="image",
            field=models.ImageField(upload_to="uploads/profiles/prof"),
        ),
        migrations.AlterField(
            model_name="informationofficer",
            name="image",
            field=models.ImageField(upload_to="uploads/profiles/prof"),
        ),
        migrations.AlterField(
            model_name="nationalcouncilhead",
            name="image",
            field=models.ImageField(upload_to="uploads/profiles/prof"),
        ),
        migrations.AlterField(
            model_name="officerprofile",
            name="image",
            field=models.ImageField(upload_to="uploads/profiles/prof"),
        ),
        migrations.AlterField(
            model_name="officerprofile",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="officershead",
            name="image",
            field=models.ImageField(upload_to="uploads/profiles/prof"),
        ),
        migrations.AlterField(
            model_name="officersspokesperson",
            name="image",
            field=models.ImageField(upload_to="uploads/profiles/prof"),
        ),
    ]
