# Generated by Django 5.0.4 on 2024-05-13 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0005_executivecommittehead_order_informationofficer_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commiteprofile",
            name="image",
            field=models.ImageField(
                upload_to="uploads/profiles/prof",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="executivecommittehead",
            name="image",
            field=models.ImageField(
                upload_to="uploads/profiles/prof",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="informationofficer",
            name="image",
            field=models.ImageField(
                upload_to="uploads/profiles/prof",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nationalcouncilhead",
            name="image",
            field=models.ImageField(
                upload_to="uploads/profiles/prof",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="officerprofile",
            name="image",
            field=models.ImageField(
                upload_to="uploads/profiles/prof",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="officershead",
            name="image",
            field=models.ImageField(
                upload_to="uploads/profiles/prof",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="officersspokesperson",
            name="image",
            field=models.ImageField(
                upload_to="uploads/profiles/prof",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
