# Generated by Django 5.0.4 on 2024-05-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_alter_commiteprofile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commiteprofile",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="profiles.designation"
            ),
        ),
        migrations.AlterField(
            model_name="executivecommittehead",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="profiles.designation"
            ),
        ),
        migrations.AlterField(
            model_name="informationofficer",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="profiles.designation"
            ),
        ),
        migrations.AlterField(
            model_name="nationalcouncilhead",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="profiles.designation"
            ),
        ),
        migrations.AlterField(
            model_name="officerprofile",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="profiles.designation"
            ),
        ),
        migrations.AlterField(
            model_name="officershead",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="profiles.designation"
            ),
        ),
        migrations.AlterField(
            model_name="officersspokesperson",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="profiles.designation"
            ),
        ),
        migrations.AlterField(
            model_name="trainings",
            name="training_org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="profiles.trainingorg"
            ),
        ),
    ]
