# Generated by Django 5.0.4 on 2024-05-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_alter_commiteprofile_id_alter_department_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officerprofile",
            name="trainings",
            field=models.ManyToManyField(blank=True, to="profiles.trainings"),
        ),
    ]
