# Generated by Django 5.0.4 on 2024-05-15 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_alter_officerprofile_trainings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commiteprofile",
            options={
                "verbose_name": "Committee Profile",
                "verbose_name_plural": "Committee Profilee List",
            },
        ),
        migrations.AlterModelOptions(
            name="executivecommittehead",
            options={
                "verbose_name": "Executive Committee Head",
                "verbose_name_plural": "Executive Committee Head List",
            },
        ),
        migrations.AlterModelOptions(
            name="informationofficer",
            options={
                "verbose_name": "Information Officer Person",
                "verbose_name_plural": "Information Officers List",
            },
        ),
        migrations.AlterModelOptions(
            name="nationalcouncilhead",
            options={
                "verbose_name": "National Council Head",
                "verbose_name_plural": "National Council Head List",
            },
        ),
        migrations.AlterModelOptions(
            name="officerprofile",
            options={
                "verbose_name": "Officer Profile",
                "verbose_name_plural": "Officer Profile List",
            },
        ),
        migrations.AlterModelOptions(
            name="officershead",
            options={
                "verbose_name": "Officers Head",
                "verbose_name_plural": "Officers Head List",
            },
        ),
        migrations.AlterModelOptions(
            name="officersspokesperson",
            options={
                "verbose_name": "Officers Spokes Person",
                "verbose_name_plural": "Officers Spokes Person List",
            },
        ),
        migrations.AlterModelOptions(
            name="skills",
            options={"verbose_name": "Skill", "verbose_name_plural": "Skills"},
        ),
        migrations.AlterModelOptions(
            name="trainings",
            options={"verbose_name": "Training", "verbose_name_plural": "Trainings"},
        ),
    ]
