# Generated by Django 5.0.4 on 2024-05-16 04:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_alter_commiteprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="informationofficer",
            options={
                "verbose_name": "Information Officer Person",
                "verbose_name_plural": "Information  Officers List",
            },
        ),
    ]
