# Generated by Django 5.0.4 on 2024-05-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_informationofficer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officerprofile",
            name="mobile",
            field=models.CharField(max_length=255),
        ),
    ]
