# Generated by Django 5.0.4 on 2024-05-17 07:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_alter_officerprofile_mobile"),

    ]

    operations = [
        migrations.AlterField(
            model_name="commiteprofile",
            name="additional_info",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info"
            ),
        ),
        migrations.AlterField(
            model_name="commiteprofile",
            name="additional_info_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info_ne"
            ),
        ),
        migrations.AlterField(
            model_name="executivecommittehead",
            name="additional_info",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info"
            ),
        ),
        migrations.AlterField(
            model_name="executivecommittehead",
            name="additional_info_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info_ne"
            ),
        ),
        migrations.AlterField(
            model_name="informationofficer",
            name="additional_info",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info"
            ),
        ),
        migrations.AlterField(
            model_name="informationofficer",
            name="additional_info_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info_ne"
            ),
        ),
        migrations.AlterField(
            model_name="nationalcouncilhead",
            name="additional_info",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info"
            ),
        ),
        migrations.AlterField(
            model_name="nationalcouncilhead",
            name="additional_info_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info_ne"
            ),
        ),
        migrations.AlterField(
            model_name="officerprofile",
            name="additional_info",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="additional_info"
            ),
        ),
        migrations.AlterField(
            model_name="officerprofile",
            name="additional_info_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="additional_info_ne"
            ),
        ),
        migrations.AlterField(
            model_name="officershead",
            name="additional_info",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info"
            ),
        ),
        migrations.AlterField(
            model_name="officershead",
            name="additional_info_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info_ne"
            ),
        ),
        migrations.AlterField(
            model_name="officersspokesperson",
            name="additional_info",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info"
            ),
        ),
        migrations.AlterField(
            model_name="officersspokesperson",
            name="additional_info_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="additional_info_ne"
            ),
        ),
        migrations.AlterField(
            model_name="trainings",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="trainings",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="description_ne"
            ),
        ),
    ]
