# Generated by Django 5.0.4 on 2024-04-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("title_ne", models.CharField(max_length=255)),
                ("photo_credit", models.CharField(max_length=255)),
                ("photo_credit_ne", models.CharField(max_length=255)),
                ("caption", models.TextField()),
                ("caption_ne", models.TextField()),
                ("image", models.ImageField(upload_to="uploads/gallery")),
            ],
        ),
        migrations.CreateModel(
            name="DisplayImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("title_ne", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="uploads/display_image")),
                ("other_images", models.ManyToManyField(to="galleries.gallery")),
            ],
        ),
    ]
