# Generated by Django 5.0.4 on 2024-04-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galleries", "0003_alter_galleryimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
