# Generated by Django 5.0.4 on 2024-04-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galleries", "0004_alter_gallery_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoGallery",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("youtube_url", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(upload_to="uploads/gallery/display_image/"),
        ),
    ]
