# Generated by Django 5.0.4 on 2024-05-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galleries", "0005_videogallery_alter_gallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="gallery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="images",
                to="galleries.gallery",
            ),
        ),
    ]
