# Generated by Django 5.0.4 on 2024-05-15 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galleries", "0008_alter_gallery_id_alter_galleryimage_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Gallery", "verbose_name_plural": "Galleries"},
        ),
        migrations.AlterModelOptions(
            name="galleryimage",
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.AlterModelOptions(
            name="videogallery",
            options={
                "verbose_name": "Video Gallery",
                "verbose_name_plural": "Video Galleries",
            },
        ),
    ]
