# Generated by Django 5.0.4 on 2024-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galleries", "0009_alter_gallery_options_alter_galleryimage_options_and_more"),

    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="caption_ne",
            field=models.TextField(blank=True, null=True),
        ),
    ]
