# Generated by Django 5.0.4 on 2024-04-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hazards",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255)),
                ("title_ne", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
                ("description", models.TextField()),
                ("icon", models.ImageField(upload_to="hazard_icons/")),
                ("color", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Natural", "Natural"),
                            ("Non-Natural", "Non-Natural"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
