# Generated by Django 5.0.4 on 2024-05-13 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hazard", "0002_alter_hazards_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazards",
            name="icon",
            field=models.ImageField(
                upload_to="uplods/hazard_icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
