# Generated by Django 5.0.4 on 2024-05-14 03:44

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hazard", "0003_alter_hazards_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazards",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="hazards",
            name="order",
            field=models.IntegerField(unique=True),
        ),
    ]
