# Generated by Django 5.0.4 on 2024-05-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hazard", "0004_alter_hazards_description_alter_hazards_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazards",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
