# Generated by Django 5.0.4 on 2024-05-15 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hazard", "0005_alter_hazards_id"),

    ]

    operations = [
        migrations.AlterModelOptions(
            name="hazards",
            options={"verbose_name": "Hazard",
                     "verbose_name_plural": "Hazards"},

        ),
    ]
