# Generated by Django 5.0.4 on 2024-04-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("title_ne", models.TextField()),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/page/featured_image"
                    ),
                ),
                ("description", models.TextField()),
                ("description_ne", models.TextField()),
                ("slug", models.SlugField()),
            ],
        ),
    ]
