# Generated by Django 5.0.4 on 2024-04-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmarks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("name_ne", models.TextField()),
                ("link", models.URLField()),
            ],
        ),
    ]
