# Generated by Django 5.0.4 on 2024-04-30 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "publication",
            "0002_publications_description_publications_description_ne_and_more",
        ),
        ("website", "0003_bookmarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("name_ne", models.TextField()),
                ("link", models.CharField(blank=True, max_length=100, null=True)),
                ("is_external_link", models.BooleanField(default=False)),
                ("page", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "content_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publication.publications",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="website.menu",
                    ),
                ),
            ],
        ),
    ]
