# Generated by Django 5.0.4 on 2024-05-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_contactform"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageBanner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("title_ne", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="uploads/homepage/banner")),
            ],
        ),
    ]
