# Generated by Django 5.0.4 on 2024-05-13 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_homepagebanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagebanner",
            name="image",
            field=models.ImageField(
                upload_to="uploads/homepage/banner",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/page/featured_image",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
