# Generated by Django 5.0.4 on 2024-05-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_alter_contactdetail_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdetail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
