# Generated by Django 5.0.4 on 2024-05-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0012_alter_bookmarks_id_alter_frequentlyaskedquestions_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="warddocument",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/ward_document/pdf_preview_image",
            ),
        ),
    ]
