# Generated by Django 5.0.4 on 2024-05-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_warddocument_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warddocument",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/ward_document_images"
            ),
        ),
    ]
