# Generated by Django 5.0.4 on 2024-05-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_alter_warddocument_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="NdrmaPortals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="ndrmaPortal/icons/")),
                ("realted_link", models.URLField()),
            ],
            options={
                "verbose_name": "Ndrma Portal",
                "verbose_name_plural": "Ndrma Portals List",
            },
        ),
        migrations.AlterModelOptions(
            name="bookmarks",
            options={"verbose_name": "Bookmark", "verbose_name_plural": "Bookmarks"},
        ),
        migrations.AlterModelOptions(
            name="contactdetail",
            options={
                "verbose_name": "Contact Detail",
                "verbose_name_plural": "Contact Detail List",
            },
        ),
        migrations.AlterModelOptions(
            name="frequentlyaskedquestions",
            options={
                "verbose_name": "Frequently Asked Question",
                "verbose_name_plural": "Frequently Asked Questions",
            },
        ),
    ]
