# Generated by Django 5.0.4 on 2024-05-16 07:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_ndrmaportals_alter_bookmarks_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdetail",
            name="detail",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Detail"),
        ),
        migrations.AlterField(
            model_name="contactdetail",
            name="detail_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Detail_ne"),
        ),
        migrations.AlterField(
            model_name="frequentlyaskedquestions",
            name="answer",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="answer"),
        ),
        migrations.AlterField(
            model_name="frequentlyaskedquestions",
            name="answer_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="answer_ne"),
        ),
        migrations.AlterField(
            model_name="frequentlyaskedquestions",
            name="question",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="question"),
        ),
        migrations.AlterField(
            model_name="frequentlyaskedquestions",
            name="question_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="question_ne"),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="content_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="content_ne"),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="description_ne"
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="description_ne"
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="sub_title",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="subtitle"),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="sub_title_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="subtitle_ne"),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="title",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="title_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="title_ne"),
        ),
        migrations.AlterField(
            model_name="page",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="page",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="description_ne"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="page",
            name="title_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="title_ne"),
        ),
    ]
