# Generated by Django 5.0.4 on 2024-05-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_alter_contactdetail_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
