# Generated by Django 5.0.4 on 2024-05-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_alter_page_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="page",
            name="title_ne",
            field=models.CharField(max_length=255),
        ),
    ]
