# Generated by Django 5.0.4 on 2024-04-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MohaPhoneDirectoryList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('division_section', models.TextField()),
                ('division_section_ne', models.TextField()),
                ('phone', models.CharField(null=True)),
                ('mobile', models.CharField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceWiseFocalPersonContactList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.IntegerField(choices=[(1, 'Proince 1'), (2, 'Proince 2'), (3, 'Proince 3'), (4, 'Proince 4'), (5, 'Proince 5'), (6, 'Proince 6'), (7, 'Proince 7')])),
                ('designation', models.CharField(max_length=100)),
                ('designation_ne', models.CharField(max_length=100)),
                ('govt_contact_person_name', models.CharField(max_length=100)),
                ('govt_contact_person_name_ne', models.CharField(max_length=100)),
                ('govt_contact_person_mobile', models.CharField(max_length=20)),
                ('govt_contact_person_email', models.EmailField(max_length=254)),
                ('province_focal_point_agency', models.CharField(max_length=100)),
                ('agency_contact_person_name', models.CharField(max_length=100)),
                ('agency_contact_person_name_ne', models.CharField(max_length=100)),
                ('agency_contact_person_mobile', models.CharField(max_length=20)),
                ('agency_contact_person_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
