# Generated by Django 5.0.4 on 2024-04-26 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importantcontacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MohaSubordinateList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_ne', models.TextField()),
                ('address', models.TextField()),
                ('address_ne', models.TextField()),
                ('phone', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mohaphonedirectorylist',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mohaphonedirectorylist',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DeocHeadList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('designation_ne', models.CharField(max_length=100)),
                ('office_landline_no', models.CharField(max_length=10)),
                ('fax_no', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importantcontacts.district')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('municipality_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importantcontacts.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importantcontacts.province')),
            ],
        ),
        migrations.CreateModel(
            name='LocalDisasterManagementContactList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('contact_num', models.CharField(max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importantcontacts.district')),
                ('municcipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importantcontacts.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importantcontacts.province')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importantcontacts.province'),
        ),
    ]
