# Generated by Django 5.0.4 on 2024-04-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0001_initial'),
        ('importantcontacts', '0003_alter_provincewisefocalpersoncontactlist_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='district',
        ),
        migrations.AlterField(
            model_name='localdisastermanagementcontactlist',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='federal.district'),
        ),
        migrations.AlterField(
            model_name='deocheadlist',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='federal.district'),
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='province',
        ),
        migrations.AlterField(
            model_name='localdisastermanagementcontactlist',
            name='municcipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='federal.municipality'),
        ),
        migrations.AlterField(
            model_name='localdisastermanagementcontactlist',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='federal.province'),
        ),
        migrations.AlterField(
            model_name='provincewisefocalpersoncontactlist',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='federal.province'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
