# Generated by Django 5.0.4 on 2024-04-26 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importantcontacts', '0004_remove_municipality_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mohaphonedirectorylist',
            name='phone',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
    ]
