# Generated by Django 5.0.4 on 2024-04-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importantcontacts', '0006_alter_mohaphonedirectorylist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deocheadlist',
            name='fax_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deocheadlist',
            name='mobile_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deocheadlist',
            name='office_landline_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='localdisastermanagementcontactlist',
            name='contact_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mohaphonedirectorylist',
            name='mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mohaphonedirectorylist',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
