# Generated by Django 5.0.4 on 2024-04-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importantcontacts', '0007_alter_deocheadlist_fax_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincewisefocalpersoncontactlist',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
