# Generated by Django 5.0.4 on 2024-04-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importantcontacts', '0008_alter_provincewisefocalpersoncontactlist_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deocheadlist',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deocheadlist',
            name='designation_ne',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deocheadlist',
            name='fax_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deocheadlist',
            name='mobile_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deocheadlist',
            name='office_landline_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='localdisastermanagementcontactlist',
            name='contact_num',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mohaphonedirectorylist',
            name='mobile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mohaphonedirectorylist',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='provincewisefocalpersoncontactlist',
            name='agency_contact_person_mobile',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provincewisefocalpersoncontactlist',
            name='agency_contact_person_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provincewisefocalpersoncontactlist',
            name='agency_contact_person_name_ne',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provincewisefocalpersoncontactlist',
            name='designation_ne',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provincewisefocalpersoncontactlist',
            name='govt_contact_person_mobile',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provincewisefocalpersoncontactlist',
            name='govt_contact_person_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provincewisefocalpersoncontactlist',
            name='govt_contact_person_name_ne',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provincewisefocalpersoncontactlist',
            name='province_focal_point_agency',
            field=models.CharField(max_length=255),
        ),
    ]
