# Generated by Django 5.0.4 on 2024-04-29 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federal", "0002_district_code_district_district_name_ne_and_more"),
        ("importantcontacts", "0009_alter_deocheadlist_designation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnakeBites",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("treatment_centre", models.CharField(max_length=255)),
                ("treatment_centre_ne", models.CharField(max_length=255)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="federal.district",
                    ),
                ),
            ],
        ),
    ]
