# Generated by Django 5.0.4 on 2024-04-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federal", "0002_district_code_district_district_name_ne_and_more"),
        ("importantcontacts", "0010_snakebites"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyVehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Ambulance", "Ambulance"),
                            ("Fire_truck", "Fire_truck"),
                            ("Police_vehicle", "Police_vehicle"),
                        ],
                        max_length=255,
                    ),
                ),
                ("ownership", models.CharField(blank=True, max_length=255)),
                ("ownership_ne", models.CharField(blank=True, max_length=255)),
                ("vechicle_no", models.CharField(blank=True, max_length=255)),
                ("vechicle_no_ne", models.CharField(blank=True, max_length=255)),
                ("driver_name", models.CharField(blank=True, max_length=255)),
                ("driver_name_ne", models.CharField(blank=True, max_length=255)),
                ("contact", models.CharField(blank=True, max_length=255)),
                ("alt_contact", models.CharField(blank=True, max_length=255)),
                ("condition", models.TextField()),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="federal.district",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="federal.municipality",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="federal.province",
                    ),
                ),
            ],
        ),
    ]
