# Generated by Django 5.0.4 on 2024-05-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "federal",
            "0004_alter_district_province_alter_municipality_district_and_more",
        ),
        ("importantcontacts", "0011_emergencyvehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deocheadlist",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.district"
            ),
        ),
        migrations.AlterField(
            model_name="emergencyvehicle",
            name="district",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="federal.district",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyvehicle",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="federal.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyvehicle",
            name="province",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="federal.province",
            ),
        ),
        migrations.AlterField(
            model_name="localdisastermanagementcontactlist",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.district"
            ),
        ),
        migrations.AlterField(
            model_name="localdisastermanagementcontactlist",
            name="municcipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.municipality"
            ),
        ),
        migrations.AlterField(
            model_name="localdisastermanagementcontactlist",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.province"
            ),
        ),
        migrations.AlterField(
            model_name="provincewisefocalpersoncontactlist",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.province"
            ),
        ),
        migrations.AlterField(
            model_name="snakebites",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.district"
            ),
        ),
    ]
