# Generated by Django 5.0.4 on 2024-05-14 03:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("importantcontacts", "0012_alter_deocheadlist_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencyvehicle",
            name="condition",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="mohaphonedirectorylist",
            name="division_section",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="mohaphonedirectorylist",
            name="division_section_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="mohasubordinatelist",
            name="address",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="mohasubordinatelist",
            name="address_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="mohasubordinatelist",
            name="name",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="mohasubordinatelist",
            name="name_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="mohasubordinatelist",
            name="phone",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Text"
            ),
        ),
    ]
