# Generated by Django 5.0.4 on 2024-04-29 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuideCourse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("title_ne", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("description_ne", models.TextField()),
                ("image", models.ImageField(upload_to="uploads/guide_course")),
            ],
        ),
        migrations.CreateModel(
            name="Guidechildren",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("name_ne", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("title_ne", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("description_ne", models.TextField()),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guidecourse.guidecourse",
                    ),
                ),
            ],
        ),
    ]
