# Generated by Django 5.0.4 on 2024-04-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guidecourse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidechildren",
            name="image",
            field=models.ImageField(
                default=None, null=True, upload_to="uploads/guide_course/children/"
            ),
        ),
    ]
