# Generated by Django 5.0.4 on 2024-04-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guidecourse", "0002_guidechildren_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guidechildren",
            name="parent",
        ),
        migrations.AddField(
            model_name="guidechildren",
            name="parent",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="guidecourse.guidecourse"
            ),
        ),
    ]
