# Generated by Django 5.0.4 on 2024-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guidecourse", "0003_remove_guidechildren_parent_guidechildren_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("title_ne", models.CharField(max_length=255)),
                ("path", models.URLField()),
                ("image", models.ImageField(upload_to="uploads/guide_course/course")),
                ("youtube_url", models.URLField()),
                ("description", models.TextField()),
                ("description_ne", models.TextField()),
                ("target_audience", models.TextField()),
                ("target_audience_ne", models.TextField()),
                ("duration", models.CharField(max_length=55)),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("English", "English"), ("Nepali", "Nepali")],
                        max_length=20,
                    ),
                ),
                ("learning_objective", models.TextField()),
                ("learning_objective_ne", models.TextField()),
            ],
        ),
    ]
