# Generated by Django 5.0.4 on 2024-05-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "guidecourse",
            "0005_alter_course_description_alter_course_description_ne_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="guidechildren",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="guidecourse",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
