# Generated by Django 5.0.4 on 2024-05-15 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guidecourse", "0006_alter_course_id_alter_guidechildren_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="guidechildren",
            options={
                "verbose_name": "Guide Children",
                "verbose_name_plural": "Guide Childrens",
            },
        ),
        migrations.AlterModelOptions(
            name="guidecourse",
            options={"verbose_name": "Gallery", "verbose_name_plural": "Galleries"},
        ),
    ]
