# Generated by Django 5.0.4 on 2024-05-16 04:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "guidecourse",
            "0007_alter_course_options_alter_guidechildren_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guidecourse",
            options={"verbose_name": "Guide", "verbose_name_plural": "Guides"},
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description_ne"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_objective",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="learning_objective"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_objective_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="learning_objective_ne"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="target_audience",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Target_audience"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="target_audience_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Target_audience_ne"
            ),
        ),
        migrations.AlterField(
            model_name="guidechildren",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="guidechildren",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description_ne"
            ),
        ),
    ]
