# Generated by Django 5.0.4 on 2024-05-16 11:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "guidecourse",
            "0008_alter_guidecourse_options_alter_course_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidecourse",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="guidecourse",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="description_ne"
            ),
        ),
    ]
