# Generated by Django 5.0.4 on 2024-04-26 09:28

import django.db.models.deletion
import officerprofileinfos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officerprofileinfos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='officer',
            name='image',
            field=models.ImageField(upload_to=officerprofileinfos.models.get_upload_path_officer),
        ),
        migrations.CreateModel(
            name='ExecutiveCommitteeHead',
            fields=[
                ('leadership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='officerprofileinfos.leadership')),
            ],
            bases=('officerprofileinfos.leadership',),
        ),
        migrations.CreateModel(
            name='InformationOfficer',
            fields=[
                ('leadership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='officerprofileinfos.leadership')),
            ],
            bases=('officerprofileinfos.leadership',),
        ),
        migrations.CreateModel(
            name='NationalCouncilHead',
            fields=[
                ('leadership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='officerprofileinfos.leadership')),
            ],
            bases=('officerprofileinfos.leadership',),
        ),
        migrations.CreateModel(
            name='OfficersHead',
            fields=[
                ('leadership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='officerprofileinfos.leadership')),
            ],
            bases=('officerprofileinfos.leadership',),
        ),
        migrations.CreateModel(
            name='OfficersSpokesperson',
            fields=[
                ('leadership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='officerprofileinfos.leadership')),
            ],
            bases=('officerprofileinfos.leadership',),
        ),
        migrations.AddField(
            model_name='leadership',
            name='officer_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='officerprofileinfos.officer'),
        ),
    ]
