# Generated by Django 5.0.4 on 2024-05-13 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "federal",
            "0004_alter_district_province_alter_municipality_district_and_more",
        ),
        ("trainingprojects", "0003_alter_donater_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="donater",
            name="donater_created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_donaters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="trainingprojects.address",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.district"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="trainingprojects.donater",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="trainingprojects.address",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.district"
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="federal.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.province"
            ),
        ),
    ]
