# Generated by Django 5.0.4 on 2024-05-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainingprojects", "0008_alter_donater_donater_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donater",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
