# Generated by Django 5.0.4 on 2024-05-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainingprojects", "0009_alter_donater_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donater",
            name="donater_deleted_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="deleted_at",
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
