# Generated by Django 5.0.4 on 2024-05-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federal", "0006_alter_district_options_alter_municipality_options_and_more"),
        ("trainingprojects", "0010_remove_donater_donater_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="federal.municipality",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="federal.province",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="federal.district",
            ),
        ),
    ]
