# Generated by Django 5.0.4 on 2024-05-17 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federal", "0006_alter_district_options_alter_municipality_options_and_more"),
        ("trainingprojects", "0011_project_municipality_project_province_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="fiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=255)),
                ("year_ne", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GeoHazardAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_ne", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="federal.district",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trainingprojects.fiscal",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="federal.municipality",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="federal.province",
                    ),
                ),
            ],
        ),
    ]
