# Generated by Django 5.0.4 on 2024-05-17 07:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trainingprojects", "0013_alter_geohazardassessment_file"),

    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Description_ne"
            ),
        ),
    ]
