# Generated by Django 5.0.4 on 2024-04-30 05:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("federal", "0002_district_code_district_district_name_ne_and_more"),
        ("hazard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("point", models.CharField()),
                ("createdOn", models.DateTimeField(default=django.utils.timezone.now)),
                ("titleNe", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("verified", models.BooleanField(default=False)),
                ("public", models.BooleanField(default=False)),
                ("startedOn", models.DateTimeField()),
                ("expireOn", models.DateTimeField(blank=True, null=True)),
                ("polygon", models.CharField(blank=True, null=True)),
                ("referenceType", models.CharField(max_length=255)),
                ("referenceData", models.TextField()),
                ("referenceId", models.IntegerField()),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("regionId", models.IntegerField(blank=True, null=True)),
                ("event", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hazard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hazard.hazards",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wards",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="federal.ward",
                    ),
                ),
            ],
        ),
    ]
