# Generated by Django 5.0.4 on 2024-05-02 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Alerts", "0002_alter_alertlist_event"),
        ("federal", "0003_alter_district_code_alter_province_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertlist",
            name="wards",
            field=models.ForeignKey(
                default=101,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="federal.ward",
            ),
        ),
    ]
