# Generated by Django 5.0.4 on 2024-05-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Alerts", "0003_alter_alertlist_wards"),
        (
            "federal",
            "0004_alter_district_province_alter_municipality_district_and_more",
        ),
        ("hazard", "0003_alter_hazards_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertlist",
            name="hazard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="hazard.hazards"
            ),
        ),
        migrations.AlterField(
            model_name="alertlist",
            name="wards",
            field=models.ForeignKey(
                default=101,
                on_delete=django.db.models.deletion.PROTECT,
                to="federal.ward",
            ),
        ),
    ]
