# Generated by Django 5.0.4 on 2024-05-14 03:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Alerts", "0004_alter_alertlist_hazard_alter_alertlist_wards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertlist",
            name="referenceData",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
