# Generated by Django 5.0.4 on 2024-05-14 03:30

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Alerts", "0005_alter_alertlist_referencedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertlist",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="alertlist",
            name="referenceData",
            field=models.TextField(),
        ),
    ]
