# Generated by Django 5.0.4 on 2024-05-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Alerts", "0006_alter_alertlist_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
