# Generated by Django 5.0.4 on 2024-05-15 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Alerts", "0007_alter_alertlist_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alertlist",
            options={"verbose_name": "Alert", "verbose_name_plural": "Alerts"},
        ),
    ]
