# Generated by Django 5.0.4 on 2024-05-15 08:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Alerts", "0008_alter_alertlist_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertlist",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
    ]
