# Generated by Django 5.0.4 on 2024-04-26 07:16

import bulletin.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('author_ne', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BulletinType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bulletin_type', models.CharField(max_length=50)),
                ('bulletin_type_ne', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_ne', models.TextField()),
                ('summary', models.TextField()),
                ('summary_ne', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=bulletin.models.get_upload_path_bulletin)),
                ('bulletin_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bulletin.bulletinauthor')),
                ('bulletin_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bulletin.bulletintype')),
            ],
        ),
    ]
