# Generated by Django 5.0.4 on 2024-04-30 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bulletin",
            name="description_ne",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bulletin",
            name="file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="uploads/bulletin/files/"
            ),
            preserve_default=False,
        ),
    ]
