# Generated by Django 5.0.4 on 2024-05-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletin", "0002_bulletin_description_bulletin_description_ne_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
