# Generated by Django 5.0.4 on 2024-05-13 04:10

import bulletin.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletin", "0003_bulletin_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletin",
            name="file",
            field=models.FileField(
                upload_to="uploads/bulletin/files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bulletin",
            name="image",
            field=models.ImageField(
                upload_to=bulletin.models.get_upload_path_bulletin,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
