# Generated by Django 5.0.4 on 2024-05-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletin", "0004_alter_bulletin_file_alter_bulletin_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletintype",
            name="bulletin_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bulletintype",
            name="bulletin_type_ne",
            field=models.CharField(max_length=255),
        ),
    ]
