# Generated by Django 5.0.4 on 2024-05-15 05:57

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletin", "0009_alter_bulletinauthor_id_alter_bulletintype_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletin",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="bulletin",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Description_ne"
            ),
        ),
        migrations.AlterField(
            model_name="bulletin",
            name="summary",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Summary"),
        ),
        migrations.AlterField(
            model_name="bulletin",
            name="summary_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Summary_ne"),
        ),
        migrations.AlterField(
            model_name="bulletin",
            name="title_ne",
            field=models.TextField(),
        ),
    ]
