# Generated by Django 5.0.4 on 2024-05-15 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletin", "0010_alter_bulletin_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletin",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/bulletin/files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
