# Generated by Django 5.0.4 on 2024-04-30 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("federal", "0002_district_code_district_district_name_ne_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loss",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("peopleDeathCount", models.IntegerField(default=0)),
                ("peopleDeathMaleCount", models.IntegerField(default=0)),
                ("peopleDeathFemaleCount", models.IntegerField(default=0)),
                ("peopleDeathOtherCount", models.IntegerField(default=0)),
                ("peopleDeathUnknownCount", models.IntegerField(default=0)),
                ("peopleDeathDisabledCount", models.IntegerField(default=0)),
                ("peopleMissingCount", models.IntegerField(default=0)),
                ("peopleMissingMaleCount", models.IntegerField(default=0)),
                ("peopleMissingFemaleCount", models.IntegerField(default=0)),
                ("peopleMissingOtherCount", models.IntegerField(default=0)),
                ("peopleMissingUnknownCount", models.IntegerField(default=0)),
                ("peopleMissingDisabledCount", models.IntegerField(default=0)),
                ("peopleInjuredCount", models.IntegerField(default=0)),
                ("peopleInjuredMaleCount", models.IntegerField(default=0)),
                ("peopleInjuredFemaleCount", models.IntegerField(default=0)),
                ("peopleInjuredOtherCount", models.IntegerField(default=0)),
                ("peopleInjuredUnknownCount", models.IntegerField(default=0)),
                ("peopleInjuredDisabledCount", models.IntegerField(default=0)),
                ("peopleAffectedCount", models.IntegerField(default=0)),
                ("familyAffectedCount", models.IntegerField(default=0)),
                ("familyRelocatedCount", models.IntegerField(default=0)),
                ("familyEvacuatedCount", models.IntegerField(default=0)),
                ("livestockDestroyedCount", models.IntegerField(default=0)),
                ("infrastructureDestroyedCount", models.IntegerField(default=0)),
                ("infrastructureDestroyedHouseCount", models.IntegerField(default=0)),
                ("infrastructureAffectedHouseCount", models.IntegerField(default=0)),
                ("infrastructureDestroyedRoadCount", models.IntegerField(default=0)),
                ("infrastructureAffectedRoadCount", models.IntegerField(default=0)),
                ("infrastructureDestroyedBridgeCount", models.IntegerField(default=0)),
                ("infrastructureAffectedBridgeCount", models.IntegerField(default=0)),
                (
                    "infrastructureDestroyedElectricityCount",
                    models.IntegerField(default=0),
                ),
                (
                    "infrastructureAffectedElectricityCount",
                    models.IntegerField(default=0),
                ),
                (
                    "infrastructureEconomicLoss",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "agricultureEconomicLoss",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("createdOn", models.DateTimeField()),
                ("modifiedOn", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "estimatedLoss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("point", models.CharField(max_length=255)),
                ("createdOn", models.DateTimeField()),
                ("modifiedOn", models.DateTimeField()),
                ("titleNe", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("cause", models.TextField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("verificationMessage", models.TextField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
                ("polygon", models.CharField(blank=True, max_length=255, null=True)),
                ("incidentOn", models.DateTimeField()),
                ("reportedOn", models.DateTimeField()),
                ("streetAddress", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True, null=True)),
                ("needFollowup", models.BooleanField(default=False)),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("regionId", models.IntegerField(blank=True, null=True)),
                ("dataSourceId", models.IntegerField()),
                ("dataSource", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("event", models.CharField(blank=True, max_length=255, null=True)),
                ("hazard", models.IntegerField()),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("wards", models.ManyToManyField(to="federal.ward")),
                (
                    "loss",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident.loss",
                    ),
                ),
            ],
        ),
    ]
