# Generated by Django 5.0.4 on 2024-04-30 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hazard", "0001_initial"),
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="hazard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="hazard.hazards"
            ),
        ),
    ]
