# Generated by Django 5.0.4 on 2024-05-02 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0002_alter_incident_hazard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="createdOn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 2, 8, 59, 54, 598200, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Earthquake", "Earthquake"),
                    ("Hurricane", "Hurricane"),
                    ("Tornado", "Tornado"),
                    ("Flood", "Flood"),
                    ("Wildfire", "Wildfire"),
                    ("Tsunami", "Tsunami"),
                    ("Volcanic eruption", "Volcanic eruption"),
                    ("Landslide", "Landslide"),
                    ("Drought", "Drought"),
                    ("Blizzard", "Blizzard"),
                    ("Heatwave", "Heatwave"),
                    ("Avalanche", "Avalanche"),
                    ("Cyclone", "Cyclone"),
                    ("Thunderstorm", "Thunderstorm"),
                    ("Hailstorm", "Hailstorm"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="modifiedOn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 2, 8, 59, 54, 598313, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Nepal_police", "Nepal_police"),
                    ("Initial Rapid Assessment", "Initial_Rapid_Assessment"),
                    ("Other", "Other"),
                ],
                null=True,
            ),
        ),
    ]
