# Generated by Django 5.0.4 on 2024-05-13 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0003_alter_incident_createdon_alter_incident_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="createdOn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 13, 3, 38, 59, 973349, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="modifiedOn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 13, 3, 38, 59, 973538, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
