# Generated by Django 5.0.4 on 2024-05-13 05:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hazard", "0003_alter_hazards_icon"),
        ("incident", "0019_alter_incident_createdon_alter_incident_modifiedon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="createdOn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 13, 5, 43, 35, 61906, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="hazard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="hazard.hazards"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="modifiedOn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 13, 5, 43, 35, 62076, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
