# Generated by Django 5.0.4 on 2024-05-14 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0026_alter_incident_cause_alter_incident_createdon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="createdOn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 14, 3, 46, 37, 831480, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="modifiedOn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 14, 3, 46, 37, 831635, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
