# Generated by Django 5.0.4 on 2024-05-14 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0029_alter_incident_createdon_alter_incident_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="createdOn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 14, 4, 5, 7, 37694, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="modifiedOn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 14, 4, 5, 7, 37817, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
