# Generated by Django 5.0.4 on 2024-05-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0040_alter_incident_createdon_alter_incident_modifiedon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="createdOn",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="incident",
            name="modifiedOn",
            field=models.DateTimeField(),
        ),
    ]
