# Generated by Django 5.0.4 on 2024-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publications",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="publications",
            name="description_ne",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="publications",
            name="pdffile",
            field=models.FileField(default=None, upload_to="uploads/publication/pdf"),
        ),
        migrations.AlterField(
            model_name="publications",
            name="date",
            field=models.DateField(default=""),
        ),
        migrations.AlterField(
            model_name="publications",
            name="summary",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="publications",
            name="summary_ne",
            field=models.TextField(default=""),
        ),
    ]
