# Generated by Django 5.0.4 on 2024-05-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "publication",
            "0002_publications_description_publications_description_ne_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="publications",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
