# Generated by Django 5.0.4 on 2024-05-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0004_alter_publications_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publications",
            name="pub_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="publication.publicationauthor",
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="pub_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="publication.publicationtype",
            ),
        ),
    ]
