# Generated by Django 5.0.4 on 2024-05-14 03:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0006_alter_publications_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publications",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=" ", verbose_name="Text"
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=" ", verbose_name="Text"
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="summary",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=" ", verbose_name="Text"
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="summary_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=" ", verbose_name="Text"
            ),
        ),
    ]
