# Generated by Django 5.0.4 on 2024-05-16 04:12

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0009_alter_publications_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publications",
            options={},
        ),
        migrations.AlterField(
            model_name="publications",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=" ", verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=" ", verbose_name="Description_ne"
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="pub_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="publication.publicationauthor",
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="pub_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="publication.publicationtype",
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="summary",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=" ", verbose_name="Summary"
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="summary_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=" ", verbose_name="Summary_ne"
            ),
        ),
    ]
