# Generated by Django 5.0.4 on 2024-05-16 04:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0010_alter_publications_options_and_more"),

    ]

    operations = [
        migrations.AlterField(
            model_name="publications",
            name="pdffile",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="uploads/publication/pdf",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="pub_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="publication.publicationauthor",
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="pub_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="publication.publicationtype",
            ),
        ),
    ]
