# Generated by Django 5.0.4 on 2024-04-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='district_name_ne',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipality',
            name='municipality_name_ne',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='province_name_ne',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=100)),
                ('ward_name_ne', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.district')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.province')),
            ],
        ),
    ]
