# Generated by Django 5.0.4 on 2024-05-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federal", "0002_district_code_district_district_name_ne_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="province",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
