# Generated by Django 5.0.4 on 2024-05-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federal", "0003_alter_district_code_alter_province_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.province"
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.district"
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.province"
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.district"
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.municipality"
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="federal.province"
            ),
        ),
    ]
