# Generated by Django 5.0.4 on 2024-05-15 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("federal", "0005_alter_district_id_alter_municipality_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={"verbose_name": "District", "verbose_name_plural": "Districts"},
        ),
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "verbose_name": "Municipality",
                "verbose_name_plural": "Municipalities",
            },
        ),
        migrations.AlterModelOptions(
            name="province",
            options={"verbose_name": "Province", "verbose_name_plural": "Provinces"},
        ),
    ]
