# Generated by Django 5.0.4 on 2024-05-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "profiles",
            "0005_executivecommittehead_order_informationofficer_order_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportantLinks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="BipadAlerts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("title_ne", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("description_ne", models.TextField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "important_numbers",
                    models.ManyToManyField(to="profiles.officerprofile"),
                ),
                (
                    "important_links",
                    models.ManyToManyField(to="nationalbipadalerts.importantlinks"),
                ),
            ],
        ),
    ]
