# Generated by Django 5.0.4 on 2024-05-15 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nationalbipadalerts", "0003_alter_bipadalerts_id_alter_importantlinks_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bipadalerts",
            options={
                "verbose_name": "Bipad Alert",
                "verbose_name_plural": "Bipad Alert List",
            },
        ),
        migrations.AlterModelOptions(
            name="importantlinks",
            options={
                "verbose_name": "Important Link",
                "verbose_name_plural": "Important Link List",
            },
        ),
    ]
