# Generated by Django 5.0.4 on 2024-05-16 11:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nationalbipadalerts", "0004_alter_bipadalerts_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bipadalerts",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="bipadalerts",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description_ne"
            ),
        ),
    ]
