# Generated by Django 5.0.4 on 2024-04-29 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pressnotenews", "0002_author_type_newsinfo_author_newsinfo_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsinfo",
            name="author",
        ),
        migrations.RemoveField(
            model_name="newsinfo",
            name="type",
        ),
        migrations.CreateModel(
            name="PressNote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("title_ne", models.TextField()),
                ("description", models.TextField()),
                ("description_ne", models.TextField()),
                ("summary", models.TextField()),
                ("summary_ne", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="uploads/files/press-note")),
                ("image", models.ImageField(upload_to="uploads/images/press-note")),
                ("is_published", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pressnotenews.author",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pressnotenews.type",
                    ),
                ),
            ],
        ),
    ]
