# Generated by Django 5.0.4 on 2024-05-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pressnotenews", "0003_remove_newsinfo_author_remove_newsinfo_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressnote",
            name="image",
            field=models.ImageField(upload_to="uploads/press-note"),
        ),
    ]
