# Generated by Django 5.0.4 on 2024-05-13 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pressnotenews", "0004_alter_pressnote_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsinfo",
            name="image",
            field=models.ImageField(
                upload_to="uploads/news_info",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pressnote",
            name="file",
            field=models.FileField(
                upload_to="uploads/files/press-note",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pressnote",
            name="image",
            field=models.ImageField(
                upload_to="uploads/press-note",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
