# Generated by Django 5.0.4 on 2024-05-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pressnotenews", "0005_alter_newsinfo_image_alter_pressnote_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressnote",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pressnotenews.author",
            ),
        ),
        migrations.AlterField(
            model_name="pressnote",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pressnotenews.type",
            ),
        ),
    ]
