# Generated by Django 5.0.4 on 2024-05-17 04:45

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pressnotenews", "0008_alter_pressnote_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsinfo",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pressnote",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="newsinfo",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="newsinfo",
            name="description_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Description_ne"
            ),
        ),
        migrations.AlterField(
            model_name="newsinfo",
            name="summary",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Summary"),
        ),
        migrations.AlterField(
            model_name="newsinfo",
            name="summary_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Summary_ne"),
        ),
        migrations.AlterField(
            model_name="newsinfo",
            name="title",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="newsinfo",
            name="title_ne",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Title_ne"),
        ),
    ]
